### ISSUE TITLE
Add an isTyping bool

### ISSUE THREAD

**Issue by viveleroi** [redbluegames/unity-text-typer#13]
It would be helpful to know if text is actively being typed. For example I use a queue system for successive messages but don't want to auto-dequeue if typing is in progress. 

I personally just added `public bool IsTyping { get; private set; }` to the TextTyper and toggle it from appropriate locations.

Anyway, thanks for this lib. I was looking for something that handles colors and more critically, wrapping. So far this works well!

**Comment by edwardrowe** [comment]
Good call - thanks for submitting the issue. I added the Property. For now it just checks to see if the coroutine is assigned, so that I don't have to remember to flag it.
