### ISSUE TITLE
Some TMPro tags are not stripped, resulting in exceptions

### ISSUE THREAD

**Issue by edwardrowe** [redbluegames/unity-text-typer#24]
We need to strip *all* native tags when parsing the text, or else it will calculate the wrong number of characters to print and results in an ArgumentException.

Repro:
1. Add a <style> tag to text
2. Print it
3. Observe ArgumentException

To fix, we either need to add all missing "Unity" tags to the parser, or calculate characters to print based on the visible text. For now the easiest fix is to include all missing tags. Ex:

style
link

Another issue that could come up is you can use color like "<#FFFFFF>" instead of <color=#FFFF>. If that results in this same issue, we may want to look at solution that examines the visible text.

**Comment by edwardrowe** [comment]
For a full list of tags, see http://digitalnativestudios.com/textmeshpro/docs/rich-text/

**Comment by jushii** [comment]
https://gist.github.com/jushii/afd171d1234c0541af3cb97e6e7b2a64

This should fix all the exceptions and make the tags work. I also added a few missing ones that are not in the TMPro documentation (e.g. [gradient](https://forum.unity.com/threads/new-gradient-rich-text-tag.506635/))

**Comment by edwardrowe** [comment]
Awesome, thanks for the list!

**Comment by nguyentrong101094** [comment]
Currently, I get an exception when trying to type out this string:
"You can use Diamonds <sprite="diamond" index=0> to buy more."
I'm using version 2.2

**Comment by edwardrowe** [comment]
These should absolutely be included. There's no reason I haven't - just haven't had time to update this repository much (though it's on the top of my list for my side projects).

You are correct - changing out this line to use @jushii's gist should work: https://github.com/redbluegames/unity-text-typer/blob/bb2d53178084eeb17906b27f7f779aa983f0bdca/Assets/RedBlueGames/TextTyper/TextTagParser.cs#L22

In theory I'd also like to add these tags into my tests for tag parsing:
https://github.com/redbluegames/unity-text-typer/blob/master/Assets/RedBlueGames/TextTyper/Tests/Editor/TextTagParserTests.cs

**Comment by edwardrowe** [comment]
Should be fixed in release 2.3 https://github.com/redbluegames/unity-text-typer/releases/tag/v2.3

Thanks for the help, everyone!
