### ISSUE TITLE
Option to use in Unscaled Time / use WaitForSecondsRealtime instead

### ISSUE THREAD

**Issue by nguyentrong101094** [redbluegames/unity-text-typer#32]
I'm using this component for tutorial dialogue. There is a case where I use it in a pause screen where Time.timeScale = 0. This component doesn't work there.
I tried changing this line: 
`yield return new WaitForSeconds(this.characterPrintDelays[currPrintedChars - 1]);`
to
`yield return new WaitForSecondsRealtime(this.characterPrintDelays[currPrintedChars - 1]);`
but it leads to an exception related to the array _characterPrintDelays_.
Can you please add the option? Like a bool field to toggle using scaled time or not

**Comment by edwardrowe** [comment]
Thanks for creating this issue. The plugin should absolutely support unscaled time. We ran into this on our own project, as well.

**Comment by edwardrowe** [comment]
I've made a release with the suggested fix, but I didn't encounter the exception you saw in the test scene. If you get a chance, try it out and see if you get an error.

Release is here: https://github.com/redbluegames/unity-text-typer/releases/tag/v2.2

If you do, can you try to get me a bit more details about what you're trying to print and when?

**Comment by edwardrowe** [comment]
Again, thanks for reporting the issue and detailed request!

**Comment by nguyentrong101094** [comment]
It's working. Thank you very much!

**Comment by edwardrowe** [comment]
Rad, no problem! Thanks for submitting an issue and lighting a fire under
me 😁
