### ISSUE TITLE
Request: Add an asmdef file

### ISSUE THREAD

**Issue by kayroice** [redbluegames/unity-text-typer#39]
Hi, can someone build an asmdef for the project? Thanks.

**Comment by kayroice** [comment]
Here's an asmdef that I built for [TextTyper](https://gist.github.com/kayroice/9dbe34b8029d7af2c359fe4a9d8ec78d). I left *UseGUIDs* false so that the asmdef showed the references instead of the references' GUID.

I couldn't get this to work with the [Tests](https://github.com/redbluegames/unity-text-typer/tree/master/Assets/RedBlueGames/TextTyper/Tests) directory exposed though, even though I included references to *UnityEngine.TestRunner* and *UnityEditor.TestRunner*. Unity complained about not finding the *Test* and *TestAttribute* classes. Those classes must be provided by a different asmdef(?). When I hid the *Tests* directory from Unity this asmdef works as expected.

**Comment by edwardrowe** [comment]
Thanks for the Issue, and for the sample Assembly definition. It can definitely be inconvenient to use a plugin if it doesn't have these, so I appreciate the reminder.

The issue with the one you were using is that I think you were probably missing the [tests-specific Assembly Definition](https://docs.unity3d.com/Packages/com.unity.test-framework@1.1/manual/workflow-create-test-assembly.html).

To fix this I've added two assembly definitions to the file - one for TextTyper code and the other for the Editor tests specifically.

Let me know if those don't work for you.
